# Generated by Django 5.0.2 on 2024-02-10 19:30

import autoslug.fields
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category_image', models.ImageField(upload_to='img/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('tranding', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('image', models.ImageField(blank=True, upload_to='uploads/img/')),
                ('detail', ckeditor.fields.RichTextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('post_viewcount', models.PositiveIntegerField(default=0)),
                ('seo_keywords', models.CharField(max_length=300)),
                ('seo_description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='news.tag')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-add_time'],
            },
        ),
    ]
